### ISSUE TITLE
Prática 01

### ISSUE THREAD

**Issue by Larissamrs** [Larissamrs/GCMS-Larissa-Silva#1]
Objetivo: Criar uma issue para o professor adicionar nome como colaborador na descrição.

Link:
[README](https://github.com/Larissamrs/GCMS-Larissa-Silva/edit/main/README.md)

Observação: No Passo 3, não consigo atribuir (assign) issue ao Professor (@ramidedantas), somente quando for aceito o pedido de colaborador é que consigo realizar essa etapa.

**Comment by Larissamrs** [comment]
@ramidedantas
Passo 4: 

- [x] Atribuir issue a si mesmo (assign).
- [x] • Marcar o professor no texto da issue com @.
- [x] • Itens do checklist:
- [ ] o Instalar Git localmente
- [ ] o Criar projeto local
- [ ] o Criar repositório local e realizar commits
- [ ] o Subir alterações para o repositório remoto
- [ ] o Fazer alterações no repositório da turma

• OBS.: Quando for realizar a prática de Git, você tem a opção de marcar os itens acima diretamente na issue ou criar uma nova issue para cada item.

**Comment by ramidedantas** [comment]
@Larissamrs coloquei o nome no Readme, mas o formato está faltando bullets para colaboradores:
* Colaborador 1
* Colaborador 2

O checklist deve ser numa issue propria, e ter apenas os items abaixo (sem bullets):
- Instalar Git localmente
- Criar projeto local
- Criar repositório local e realizar commits
- Subir alterações para o repositório remoto
- Fazer alterações no repositório da turma

**Comment by Larissamrs** [comment]
@ramidedantas 
Entendi professor, vou realizar as alterçações para fins de aprendizado.
